set -g status-style "bg=default,fg=#b0b0b0"
set -g status-left "#{?client_prefix,#[fg=#d9ba73 bg=default] PREFIX #[bg=default fg=#b0b0b0],#[fg=#b0b0b0 bg=default] TMUX }  "
set -g status-right "#[fg=#b0b0b0 bg=default] %d/%m  #[fg=#d9ba73 bg=default] %H:%M "
set -g window-status-current-format "#[fg=#b0b0b0 bg=#474747] #I:#W "
set -g window-status-format "#[fg=#b0b0b0 bg=default] #I:#W "
set -g message-style "fg=#777777,bg=default"
set -g mode-style "fg=#b0b0b0,bg=#474747"
set -g pane-border-style "fg=#777777"
set -g pane-active-border-style "fg=#d9ba73"
