foreground #ffffff
background #101010
cursor #b0b0b0
selection_foreground #b0b0b0
selection_background #272727
color0 #101010
color1 #ff5733
color2 #86cd82
color3 #d9ba73
color4 #b3b3b3
color5 #f2a4db
color6 #5abfb5
color7 #a5adce
color8 #666666
color9 #ff7676
color10 #a3d6a3
color11 #ffffff
color12 #666666
color13 #f4b8e4
color14 #fafafa
color15 #b5bfe2
active_tab_foreground #101010
active_tab_background #d9ba73
inactive_tab_foreground #777777
inactive_tab_background #666666
